### ISSUE TITLE
" plasma-umass.org/ExceLint-addin " gives 404

### ISSUE THREAD

**Issue by richb-hanover** [ExceLint/ExceLint-addin#43]
**Describe the bug**
The link to [plasma-umass.org/ExceLint-addin](https://plasma-umass.org/ExceLint-addin) on this repo's home page gives a 404.

The fix would simply be to link to: [plasma-umass.org](https://plasma-umass.org/)

**To Reproduce**
_N/A_

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. Chrome, Safari]
 - Version [e.g. Excel 2016, Excel Online]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by emeryberger** [comment]
Thanks for the note. Removed the link from the repo page (not sure that plasma-umass.org would be any better).
